# 這邊記載所有的職業變數
# PALADIN
PALADIN_VAR = {
    # PASSIVE TRIGGER RATE
    'PALADIN_PASSIVE_TRIGGER_RATE': 0.1,
    # PASSIVE HEAL AMOUNT RATE
    'PALADIN_PASSIVE_HEAL_RATE': 0.1,
    # OVERHEADLING DAMAGE RATE
    'PALADIN_PASSIVE_OVERHEADLINGE_RATE': 0.1,
    
    # SKILL 1 DAMAGE AMOUNT
    'PALADIN_SKILL_1_DAMAGE': 10,
    # PALADING SKILL 2 HEAL AMOUNT AND COOLDOWN
    'PALADIN_SKILL_2_HEAL': 10,
    'PALADIN_SKILL_2_COOLDOWN': 3,
    
    # SKILL 3 DAMAGE AMOUNT
    # FIRST HEAL AMOUNT FIRST/SECOND/or more
    'PALADIN_SKILL_3_FIRST_HEAL': 10,
    'PALADIN_SKILL_3_SECOND_HEAL': 5,
    'PALADIN_SKILL_3_MORE_HEAL': 2,

}