# 這邊記載所有的職業變數
# PALADIN
PALADIN_DEFAULT_VAR = {
    # BASE STATS
    'PALADIN_BASE_HP': 387,
    'PALADIN_BASE_ATK': 1.0,
    'PALADIN_BASE_DEF': 1.15,

    
    # PASSIVE TRIGGER RATE
    'PALADIN_PASSIVE_TRIGGER_RATE': 0.3,
    # PASSIVE HEAL AMOUNT RATE
    'PALADIN_PASSIVE_HEAL_RATE': 0.15,
    # OVERHEADLING DAMAGE RATE
    'PALADIN_PASSIVE_OVERHEADLINGE_RATE': 1,
    
    # SKILL 1 DAMAGE AMOUNT
    'PALADIN_SKILL_1_DAMAGE': 40,
    # PALADING SKILL 2 HEAL AMOUNT AND COOLDOWN
    'PALADIN_SKILL_2_HEAL': 15,
    'PALADIN_SKILL_2_COOLDOWN': 3,
    
    # SKILL 3 DAMAGE AMOUNT
    # FIRST HEAL AMOUNT FIRST/SECOND/or more
    'PALADIN_SKILL_3_FIRST_HEAL': 50,
    'PALADIN_SKILL_3_SECOND_HEAL': 35,
    'PALADIN_SKILL_3_MORE_HEAL': 15,

}

PALADIN_VAR = {
    # BASE STATS
    'PALADIN_BASE_HP': 387,
    'PALADIN_BASE_ATK': 1.0,
    'PALADIN_BASE_DEF': 1.15,

    
    # PASSIVE TRIGGER RATE
    'PALADIN_PASSIVE_TRIGGER_RATE': 0.3,
    # PASSIVE HEAL AMOUNT RATE
    'PALADIN_PASSIVE_HEAL_RATE': 0.15,
    # OVERHEADLING DAMAGE RATE
    'PALADIN_PASSIVE_OVERHEADLINGE_RATE': 1,
    
    # SKILL 1 DAMAGE AMOUNT
    'PALADIN_SKILL_1_DAMAGE': 40,
    # PALADING SKILL 2 HEAL AMOUNT AND COOLDOWN
    'PALADIN_SKILL_2_HEAL': 15,
    'PALADIN_SKILL_2_COOLDOWN': 3,
    
    # SKILL 3 DAMAGE AMOUNT
    # FIRST HEAL AMOUNT FIRST/SECOND/or more
    'PALADIN_SKILL_3_FIRST_HEAL': 50,
    'PALADIN_SKILL_3_SECOND_HEAL': 35,
    'PALADIN_SKILL_3_MORE_HEAL': 15,

}